cmake_minimum_required(VERSION 3.21)

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

if(NOT DEFINED SYSTEMCORE_TOOLCHAIN_ROOT AND DEFINED ENV{SYSTEMCORE_TOOLCHAIN_ROOT})
    set(SYSTEMCORE_TOOLCHAIN_ROOT "$ENV{SYSTEMCORE_TOOLCHAIN_ROOT}")
endif()

if(NOT DEFINED SYSTEMCORE_SYSROOT AND DEFINED ENV{SYSTEMCORE_SYSROOT})
    set(SYSTEMCORE_SYSROOT "$ENV{SYSTEMCORE_SYSROOT}")
endif()

set(SYSTEMCORE_TOOLCHAIN_TRIPLE "aarch64-linux-gnu")

if(DEFINED SYSTEMCORE_TOOLCHAIN_ROOT)
    set(_TC_BIN "${SYSTEMCORE_TOOLCHAIN_ROOT}/bin")
    set(CMAKE_C_COMPILER   "${_TC_BIN}/${SYSTEMCORE_TOOLCHAIN_TRIPLE}-gcc")
    set(CMAKE_CXX_COMPILER "${_TC_BIN}/${SYSTEMCORE_TOOLCHAIN_TRIPLE}-g++")
    set(CMAKE_ASM_COMPILER "${_TC_BIN}/${SYSTEMCORE_TOOLCHAIN_TRIPLE}-gcc")
    set(CMAKE_AR           "${_TC_BIN}/${SYSTEMCORE_TOOLCHAIN_TRIPLE}-ar")
    set(CMAKE_RANLIB       "${_TC_BIN}/${SYSTEMCORE_TOOLCHAIN_TRIPLE}-ranlib")
    set(CMAKE_STRIP        "${_TC_BIN}/${SYSTEMCORE_TOOLCHAIN_TRIPLE}-strip")
    set(CMAKE_OBJCOPY      "${_TC_BIN}/${SYSTEMCORE_TOOLCHAIN_TRIPLE}-objcopy")
    set(CMAKE_OBJDUMP      "${_TC_BIN}/${SYSTEMCORE_TOOLCHAIN_TRIPLE}-objdump")
else()
    find_program(CMAKE_C_COMPILER   NAMES "${SYSTEMCORE_TOOLCHAIN_TRIPLE}-gcc" REQUIRED)
    find_program(CMAKE_CXX_COMPILER NAMES "${SYSTEMCORE_TOOLCHAIN_TRIPLE}-g++" REQUIRED)
    find_program(CMAKE_ASM_COMPILER NAMES "${SYSTEMCORE_TOOLCHAIN_TRIPLE}-gcc")
    find_program(CMAKE_AR           NAMES "${SYSTEMCORE_TOOLCHAIN_TRIPLE}-ar")
    find_program(CMAKE_RANLIB       NAMES "${SYSTEMCORE_TOOLCHAIN_TRIPLE}-ranlib")
    find_program(CMAKE_STRIP        NAMES "${SYSTEMCORE_TOOLCHAIN_TRIPLE}-strip")
    find_program(CMAKE_OBJCOPY      NAMES "${SYSTEMCORE_TOOLCHAIN_TRIPLE}-objcopy")
    find_program(CMAKE_OBJDUMP      NAMES "${SYSTEMCORE_TOOLCHAIN_TRIPLE}-objdump")
endif()

if(DEFINED SYSTEMCORE_SYSROOT)
    set(CMAKE_SYSROOT "${SYSTEMCORE_SYSROOT}")
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(_SYSTEMCORE_ARCH_FLAGS
    "-march=armv8.2-a+crypto+fp16+rcpc+dotprod -mtune=cortex-a76")

set(_SYSTEMCORE_COMMON_FLAGS
    "${_SYSTEMCORE_ARCH_FLAGS}"
    "-fPIC"
    "-fstack-protector-strong"
    "-DFORTIFY_SOURCE=2")

list(JOIN _SYSTEMCORE_COMMON_FLAGS " " _SYSTEMCORE_COMMON_FLAGS_STR)

set(CMAKE_C_FLAGS_INIT "${_SYSTEMCORE_COMMON_FLAGS_STR}")
set(CMAKE_CXX_FLAGS_INIT "${_SYSTEMCORE_COMMON_FLAGS_STR}")
set(CMAKE_ASM_FLAGS_INIT "${_SYSTEMCORE_ARCH_FLAGS}")

set(CMAKE_C_FLAGS_DEBUG_INIT            "-Og -g3 -DDEBUG")
set(CMAKE_CXX_FLAGS_DEBUG_INIT          "-Og -g3 -DDEBUG")
set(CMAKE_C_FLAGS_RELEASE_INIT          "-O2 -DNDEBUG")
set(CMAKE_CXX_FLAGS_RELEASE_INIT        "-O2 -DNDEBUG")
set(CMAKE_C_FLAGS_RELWITHDEBINFO_INIT   "-O2 -g -DNDEBUG")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT "-O2 -g -DNDEBUG")
set(CMAKE_C_FLAGS__INIT                 "-Os -DNDEBUG")
set(CMAKE_CXX_FLAGS__INIT               "-Os -DNDEBUG")

set(CMAKE_EXE_LINKER_FLAGS_INIT
    "-Wl,--export-dynamic -Wl,--as-needed -Wl,-z,relro -Wl,-z,now")

set(CMAKE_SHARED_LINKER_FLAGS_INIT "-Wl,--as-needed -Wl,-z,relro -Wl,-z,now")

set(FRC_SYSTEMCORE TRUE CACHE BOOL "Building for the limelight Systemcore" FORCE)
mark_as_advanced(FRC_SYSTEMCORE)
